### ISSUE TITLE
Is this project dead or is there a replacement for Angular 2+

### ISSUE THREAD

**Issue by ramonjsantiago** [AlphaGit/a-pattern-restrict#5]

**Comment by AlphaGit** [comment]
Hi @ramonjsantiago! Both are true -- this project is not longer under development. I do still accept and welcome contributions, though.

However (good news!) there is a version that should cover Angular 2+. You can find it here: https://github.com/AlphaGit/a-pattern-restrict/

**Comment by AlphaGit** [comment]
Hi @ramonjsantiago -- I haven't heard back from you so I'll proceed to close this question. If you need anything else, feel free to ask!
